# Generated by Django 2.2.3 on 2019-12-23 17:52

from django.db import migrations, models
import django.db.models.deletion
import fibest.Storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(help_text='This mail will be used to login to FiBEST.', max_length=254, verbose_name='Login email')),
                ('login_code', models.CharField(max_length=15)),
                ('name', models.CharField(help_text='Fullname of the company.', max_length=200, verbose_name='Fullname')),
                ('link', models.URLField(help_text='Website of the company. Example: https://www.fibest.org.', verbose_name='Website')),
                ('logo', models.ImageField(default=None, help_text='Logo for the website, ideal size is 200x100 pixels', storage=fibest.Storage.storage.OverwriteStorage(base_url='/media/logos', location='/opt/fibest/media/logos'), upload_to='', verbose_name='Logo')),
                ('stand_name', models.CharField(default='', help_text='Please indicate with what name exactly you want it to appear on the stand banner, on the maps of the forum and in the schedules of activities. It will be case sensitive.', max_length=200)),
                ('assembly_service', models.BooleanField(default=False, help_text='Based on the demands of companies participating in previous editions, we also offer a service of assembly of promotional material of your company, with a cost of € 50 (this amount will be added to the invoice of the forum services). In this way, you simply have to send the promotional materials to the organization Two days in advance, and upon arrival at the forum they will all be ready.')),
                ('disclaimer', models.BooleanField(default=False)),
                ('hasVirtualStand', models.BooleanField(default=False)),
                ('hasMagazine', models.BooleanField(default=False)),
                ('pack', models.CharField(choices=[('SP', 'Sponsor'), ('SL', 'Silver'), ('AU', 'Gold'), ('PL', 'Platinum'), ('DI', 'Diamond'), ('??', 'Custom')], help_text='Ayuda para pack', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=15)),
                ('titulation', models.IntegerField(choices=[(0, 'Grado en Administración y Dirección de Empresas'), (1, 'Grado en Arquitectura'), (2, 'Grado en Comercio'), (3, 'Grado en Criminología'), (4, 'Grado en Derecho'), (5, 'Grado en Economía'), (6, 'Grado en Educación Infantil'), (7, 'Grado en Educación Primaria'), (8, 'Grado en Educación Social'), (9, 'Grado en Enfermería'), (10, 'Grado en Enología'), (11, 'Grado en Español: Lengua y literatura'), (12, 'Grado en Estadística'), (13, 'Grado en Estudios Clásicos'), (14, 'Grado en Estudios Ingleses'), (15, 'Grado en Filosofía'), (16, 'Grado en Finanzas, Banca y Seguros'), (17, 'Grado en Fisioterapia'), (18, 'Grado en Fundamentos de Arquitectura'), (19, 'Grado en Física'), (20, 'Grado en Geografía y Ordenación del Territorio'), (21, 'Grado en Historia'), (22, 'Grado en Historia del Arte'), (23, 'Grado en Historia y Ciencias de la Música'), (24, 'Grado en Ingeniería Agraria y Energética'), (25, 'Grado en Ingeniería Agrícola y del Medio Rural'), (26, 'Grado en Ingeniería Biomédica'), (27, 'Grado en Ingeniería Eléctrica'), (28, 'Grado en Ingeniería Forestal y del Medio Natural'), (29, 'Grado en Ingeniería Forestal: Industrias forestales'), (30, 'Grado en Ingeniería Informática'), (31, 'Grado en Ingeniería Mecánica'), (32, 'Grado en Ingeniería Química'), (33, 'Grado en Ingeniería de Tecnologías Específicas de Telecomunicación'), (34, 'Grado en Ingeniería de Tecnologías de Telecomunicación'), (35, 'Grado en Ingeniería de las Industrias Agrarias y Alimentarias'), (36, 'Grado en Ingeniería en Diseño Industrial y Desarrollo de Producto'), (37, 'Grado en Ingeniería en Electrónica Industrial y Automática'), (38, 'Grado en Ingeniería en Organización Industrial'), (39, 'Grado en Ingeniería en Tecnologías Industriales'), (40, 'Grado en Lenguas Modernas y sus Literaturas'), (41, 'Grado en Logopedia'), (42, 'Grado en Marketing e Investigación de Mercados'), (43, 'Grado en Matemáticas'), (44, 'Grado en Medicina'), (45, 'Grado en Nutrición Humana y Dietética'), (46, 'Grado en Óptica y Optometría'), (47, 'Grado en Periodismo'), (48, 'Grado en Publicidad y Relaciones Públicas'), (49, 'Grado en Química'), (50, 'Grado en Relaciones Laborales y Recursos Humanos'), (51, 'Grado en Trabajo Social'), (52, 'Grado en Traducción e Interpretación'), (53, 'Grado en Turismo'), (54, 'Programa de Estudios Conjunto de Grado en Ingeniería Agrícola y del Medio Rural e Ingeniería Forestal y del Medio Natural'), (55, 'Programa de Estudios Conjunto de Grado en Ingeniería Agrícola y del Medio Rural y Grado en Ingeniería de las Industrias Agrarias y Alimentarias'), (56, 'Programa de Estudios Conjunto de Grado en Ingeniería de las Industrias Agrarias y Alimentarias y Grado en Enología'), (57, 'Programa de estudios conjunto de Grado en Derecho y Grado en Administración y Dirección de Empresas'), (58, 'Programa de estudios conjunto de Grado en Educación Infantil y Grado en Educación Primaria'), (59, 'Programa de estudios conjunto de Grado en Estadística y Grado en Ingeniería Informática'), (60, 'Programa de estudios conjunto de Grado en Física y Grado en Matemáticas'), (61, 'Programa de estudios conjunto de Grado en Ingeniería Informática de Servicios y Aplicaciones y Grado en Matemáticas'), (62, 'Programa de estudios conjunto de Grado en Ingeniería de Tecnologías de Telecomunicación y Grado en Administración y Dirección de Empresas'), (63, 'Programa de estudios conjunto de Grado en Publicidad y Relaciones Públicas y Grado en Turismo'), (64, 'Programa de estudios conjunto de Grado en Relaciones Laborales y Recursos Humanos y Grado de Administración y Dirección de Empresas')])),
                ('cv', models.FileField(upload_to='')),
                ('cover_letter', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_stand', models.CharField(blank=True, max_length=500, verbose_name='Activity of the company')),
                ('search_stand', models.CharField(blank=True, max_length=2500, verbose_name='What is your company looking for?')),
                ('year_stand', models.IntegerField(blank=True, verbose_name='Year of foundation')),
                ('workers_stand', models.IntegerField(blank=True, verbose_name='Number of workers')),
                ('location_stand', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('internships_stand', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for internships')),
                ('beca_stand', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for becas')),
                ('tfg_stand', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for TFGs')),
                ('web_contact', models.CharField(blank=True, max_length=200)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('person_contact', models.CharField(blank=True, max_length=200)),
                ('phone_contact', models.CharField(blank=True, max_length=15)),
                ('postal_contact', models.CharField(blank=True, max_length=500)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('message_stand', models.TextField(help_text='Text in which you have the opportunity to include detailed information about your mission, values, identity, offer of the company, current projects, success stories, selection process, most searched profiles etc.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibest.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publi_magazine', models.ImageField(help_text='Your company will have a complete advertising page (image in size A5) in the forum magazine. To avoid pixelated problems in printing would be convenient to send us this advertising sheet in format vector, or with a minimum resolution of 300ppp (preferable in .png format), avoiding if possible the format pdf. Remind them that the size of the magazine is A5.', storage=fibest.Storage.storage.OverwriteStorage(base_url='/media/magazine', location='/opt/fibest/media/magazine'), upload_to='', verbose_name='Image for magazine')),
                ('name_magazine', models.CharField(max_length=200, verbose_name='Name of the company (magazine)')),
                ('activity_magazine', models.CharField(max_length=500, verbose_name='Activity of the company (magazine)')),
                ('search_magazine', models.CharField(max_length=2500, verbose_name='What is your company looking for? (magazine)')),
                ('year_magazine', models.IntegerField(verbose_name='Year of foundation (magazine)')),
                ('workers_magazine', models.IntegerField(verbose_name='Number of workers (magazine)')),
                ('location_magazine', models.CharField(max_length=500, verbose_name='Location (magazine)')),
                ('internships_magazine', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for internships')),
                ('beca_magazine', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for becas')),
                ('tfg_magazine', models.CharField(blank=True, max_length=2500, verbose_name='Magazine text for TFGs')),
                ('message_magazine', models.TextField(help_text='Text in which you have the opportunity to include detailed information about your mission, values, identity, offer of the company, current projects, success stories, selection process, etc. For guidance, the appropriate size of the Text would be approximately 300 words.')),
                ('web_contact', models.CharField(max_length=200)),
                ('email_contact', models.EmailField(max_length=254)),
                ('person_contact', models.CharField(max_length=200)),
                ('phone_contact', models.CharField(max_length=15)),
                ('postal_contact', models.CharField(max_length=500)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibest.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_contract', models.CharField(help_text='Fullname of the company.', max_length=500)),
                ('cif_contract', models.CharField(help_text='CIF of the company.', max_length=15, verbose_name='CIF')),
                ('signer_contract', models.CharField(help_text='Name of the person who will sign.', max_length=200, verbose_name="signer's name")),
                ('postal_contract', models.CharField(help_text='Address where we will send the contract.', max_length=2500, verbose_name='address')),
                ('company_billing', models.CharField(help_text='Fullname of the company.', max_length=200)),
                ('cif_billing', models.CharField(max_length=15, verbose_name='Billing CIF')),
                ('postal_social_billing', models.CharField(help_text='Address where we will send the contract.', max_length=2500)),
                ('phone_billing', models.CharField(max_length=15, verbose_name='Phone number for billing')),
                ('order_number', models.CharField(default='', max_length=30, verbose_name='Order number')),
                ('postal_send_billing', models.CharField(help_text='Address where we will send the bill.', max_length=2500, verbose_name='billing address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibest.Company')),
            ],
        ),
    ]
