# Generated by Django 2.2.3 on 2020-01-25 12:24

from django.db import migrations, models
import fibest.Storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('fibest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cvs_requested',
            field=models.TextField(default='', help_text='Texto ayuda curriculums demandados', max_length=2500, verbose_name='Curriculums'),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_confirmed',
            field=models.BooleanField(default=False, verbose_name='terminos y condiciones'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='copy_magazine_info',
            field=models.BooleanField(default=False, help_text='Info copia  datos revista', verbose_name='copy magazine info'),
        ),
        migrations.AddField(
            model_name='stand',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='name_stand',
            field=models.CharField(default=None, max_length=200, verbose_name='Name of the company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='assembly_service',
            field=models.BooleanField(default=False, help_text='Based on the demands of companies participating in previous editions, we also offer a service of assembly of promotional material of your company, with a cost of € 50 (this amount will be added to the invoice of the job fair services). In this way, you simply have to send the promotional materials to the organization Two days in advance, and upon arrival at the job fair they will all be ready.', verbose_name='Assembly service'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hasMagazine',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tiene revista'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hasVirtualStand',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tiene stand virtual'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, help_text='Logo for the website, ideal size is 200x100 pixels', storage=fibest.Storage.storage.OverwriteStorage(base_url='/media/logos', location='/opt/fibest/fibest/media/logos'), upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pack',
            field=models.CharField(choices=[('SP', 'Sponsor'), ('SL', 'Silver'), ('AU', 'Gold'), ('PL', 'Platinum'), ('DI', 'Diamond'), ('??', 'Custom')], help_text='Ayuda para pack', max_length=2, verbose_name='pack'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stand_name',
            field=models.CharField(default='', help_text='Please indicate with what name exactly you want it to appear on the stand banner, on the maps of the job fair and in the schedules of activities. It will be case sensitive.', max_length=200, verbose_name='Stand name'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='cif_billing',
            field=models.CharField(max_length=15, verbose_name='CIF  of the company.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='cif_contract',
            field=models.CharField(max_length=15, verbose_name='CIF of the company.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='company_billing',
            field=models.CharField(max_length=200, verbose_name='Fullname of the company.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='company_contract',
            field=models.CharField(max_length=500, verbose_name='Fullname of the company.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='postal_contract',
            field=models.CharField(max_length=2500, verbose_name='Address where we will send the contract.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='postal_send_billing',
            field=models.CharField(max_length=2500, verbose_name='Address where we will send the bill.'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='postal_social_billing',
            field=models.CharField(max_length=2500, verbose_name='postal social billing'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='signer_contract',
            field=models.CharField(max_length=200, verbose_name='Name of the person who will sign.'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='activity_magazine',
            field=models.CharField(max_length=500, verbose_name='Activity of the company'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='beca_magazine',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for becas'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='email contact'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='internships_magazine',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for internships'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='location_magazine',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='message_magazine',
            field=models.TextField(help_text='Text in which you have the opportunity to include detailed information about your mission, values, identity, offer of the company, current projects, success stories, selection process, etc. For guidance, the appropriate size of the Text would be approximately 300 words.', verbose_name='message magazine'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='name_magazine',
            field=models.CharField(max_length=200, verbose_name='Name of the company magazine'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='person_contact',
            field=models.CharField(max_length=200, verbose_name='person contact'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='phone_contact',
            field=models.CharField(max_length=15, verbose_name='phone contact'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='postal_contact',
            field=models.CharField(max_length=500, verbose_name='postal contact'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='publi_magazine',
            field=models.ImageField(help_text='Your company will have a complete advertising page (image in size A5) in the job fair magazine. To avoid pixelated problems in printing would be convenient to send us this advertising sheet in format vector, or with a minimum resolution of 300ppp (preferable in .png format), avoiding if possible the format pdf. Remind them that the size of the magazine is A5.', storage=fibest.Storage.storage.OverwriteStorage(base_url='/media/magazine', location='/opt/fibest/fibest/media/magazine'), upload_to='', verbose_name='Image for magazine'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='search_magazine',
            field=models.CharField(max_length=2500, verbose_name='What is your company looking for?'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tfg_magazine',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for TFGs'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='web_contact',
            field=models.CharField(max_length=200, verbose_name='web contact'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='workers_magazine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of workers'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='year_magazine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of foundation'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='activity_stand',
            field=models.CharField(max_length=500, verbose_name='Activity of the company virtual'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='beca_stand',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for becas'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='email contact'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='internships_stand',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for internships'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='location_stand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='message_stand',
            field=models.TextField(help_text='Text in which you have the opportunity to include detailed information about your mission, values, identity, offer of the company, current projects, success stories, selection process, most searched profiles etc.', verbose_name='message vertual'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='person_contact',
            field=models.CharField(max_length=200, verbose_name='person contact'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='phone_contact',
            field=models.CharField(max_length=15, verbose_name='phone contact'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='postal_contact',
            field=models.CharField(max_length=500, verbose_name='postal contact'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='search_stand',
            field=models.CharField(max_length=2500, verbose_name='What is your company looking for?'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='tfg_stand',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Magazine text for TFGs'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='web_contact',
            field=models.CharField(max_length=200, verbose_name='web contact'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='workers_stand',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of workers'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='year_stand',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of foundation'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
